# Generated by Django 5.2.8 on 2025-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Player', 'Player'), ('SuperAdmin', 'SuperAdmin')], default='Player', max_length=20),
        ),
    ]
