# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_stripe_account_completed_user_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
