# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_block_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
