# Generated by Django 5.2.8 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('entry_fee', 'Entry Fee'), ('prize', 'Prize'), ('prize_lock', 'Prize Lock'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
