# Generated by Django 5.2.8 on 2026-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('stripe', 'Stripe'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
    ]
