# Generated by Django 5.2.8 on 2026-02-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentBaracket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentLeaderboard',
        ),
    ]
