# Generated by Django 5.2.8 on 2026-02-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TournamentBaracket', '0001_initial'),
        ('tournament', '0002_tournamentteam_tournamentparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField()),
                ('wwcd', models.PositiveIntegerField(default=0)),
                ('placement_points', models.PositiveIntegerField(default=0)),
                ('kill_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leaderboard_entries', to='TournamentBaracket.tournamentbracket')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leaderboard_entries', to='tournament.tournamentteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leaderboard_entries', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Group Leaderboard Entry',
                'verbose_name_plural': 'Group Leaderboard Entries',
                'ordering': ['group_name', 'rank', '-total_points', 'team__team_name'],
                'unique_together': {('tournament', 'bracket', 'group_name', 'team')},
            },
        ),
    ]
