# Generated by Django 5.2.8 on 2026-01-19 04:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_title', models.CharField(choices=[('PUBG Mobile', 'PUBG Mobile'), ('Free Fire', 'Free Fire')], max_length=50)),
                ('match_format', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('match_start', models.DateField()),
                ('expected_end', models.DateField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_generate_bracket', models.BooleanField(default=False)),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('prize_first', models.PositiveIntegerField(default=0)),
                ('prize_second', models.PositiveIntegerField(default=0)),
                ('prize_third', models.PositiveIntegerField(default=0)),
                ('match_rules', models.TextField(blank=True)),
                ('require_result_proof', models.BooleanField(default=False)),
                ('proof_type', models.CharField(choices=[('Screenshot Only', 'Screenshot Only')], default='Screenshot Only', max_length=30)),
                ('result_time_limit_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)])),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10)),
                ('auto_start_tournament', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
