# Generated by Django 5.2.8 on 2026-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentteam_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Active', 'Active'), ('Completed', 'Completed')], default='Draft', max_length=20),
        ),
    ]
