# Generated by Django 5.2.8 on 2026-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_started_at_tournament_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Active', 'Active'), ('Completed', 'Completed')], default='Registration Open', max_length=20),
        ),
    ]
