# Generated by Django 5.2.8 on 2026-03-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_fix_draft_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='proof_type',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='require_result_proof',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='result_time_limit_hours',
        ),
    ]
