# Generated by Django 5.2.8 on 2026-02-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0002_tournamentteam_tournamentparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, verbose_name='group')),
                ('match_number', models.PositiveIntegerField(verbose_name='match number')),
                ('date_time', models.DateTimeField(verbose_name='date and time')),
                ('map', models.CharField(blank=True, max_length=100, null=True, verbose_name='map')),
                ('mode', models.CharField(blank=True, max_length=100, null=True, verbose_name='mode')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['date_time'],
            },
        ),
    ]
