from rest_framework.views import expection_handler
from rest_framework.response import Response
from rest_framework import status

# Custom exception handler for API responses
def custom_exception_handler(exc, context):
    response = expection_handler(exc, context)

    # If a response is generated by DRF, customize its format
    if response is not None:
        custom_response = {
            "Status_code": response.status_code,
            "Is_Sucess": False,
            "Error_Message": response.data,
            "Result": None,
        }

        # Flatten error messages if they are in dictionary format
        if isinstance(response.data, dict):
            error_dict = {}
            for key, value in response.data.items():
                if isinstance(value, list):
                    error_dict[key] = " ".join([str(v) for v in value])
                else:
                    error_dict[key] = str(value)

            custom_response = ["Error Message"] = error_dict

        return Response(custom_response, status=response.status_code)
    
    # For unhandled exceptions, return a generic error response
    return Response(
        {
            "Status_code": status.HTTP_500_INTERNAL_SERVER_ERROR,
            "Is_Success": False,
            "Error_Message": {"details": "Internal Server Error"},
            "Result": None,
        },
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
    )





