# Generated by Django 5.2.8 on 2026-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='provider',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa')], default='khalti', max_length=20),
        ),
    ]
