# Generated by Django 5.2.8 on 2026-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_paymentorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
