# Generated by Django 5.2.8 on 2026-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_paymentorder_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_identifier',
            field=models.CharField(blank=True, help_text='eSewa ID or Khalti phone number', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='provider',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('stripe', 'Stripe')], default='stripe', max_length=20),
        ),
    ]
