# Generated by Django 5.2.8 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_withdrawalrequest_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal_receipts/'),
        ),
    ]
